name: ect_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ncbi-datasets-cli
  - muscle
  - mmseqs2
  - pip
  - pip:
      - pandas
      - numpy
      - biopython
      - dendropy
      - requests
